spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:43306/chatapp
    username: chatuser
    password: zerobase
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  token:
    secret: "p2s5v8y/B?E(H+MbQeThWmZq3t6w9z$C"